### ISSUE TITLE
Servos stuttering and getting a bit warm

### ISSUE THREAD

**Issue by zakqwy** [NeuroTinker/NeuroBytes_Motor_Neuron#1]
I 'scoped the servo PWM signal and the period is 8ms. Might need to lengthen to 20ms or more to work with the cheap 9g servos we use.

**Comment by jrwhite** [comment]
I've lengthened the PWM period to 20ms in the most recent commit. With the new motor neurons and this new PWM period, I didn't notice any stuttering or warming.

![scoped PWM](https://cloud.githubusercontent.com/assets/2604419/26067024/6503bbce-395e-11e7-8adb-9b9c2a5c164b.PNG)
