### ISSUE TITLE
change LED color and duration

### ISSUE THREAD

**Issue by zakqwy** [NeuroTinker/NeuroBytes_Motor_Neuron#8]
change from white AP flash to red/blue flash. increase flash duration to make it more obvious.

**Comment by NeuroTinkerJoe** [comment]
revert to the standard Interneuron LED scheme, maintaining the unique motor neuron behavior of incoming excitation = CW servo rotation, incoming inhibition = CCW servo rotation.

**Comment by zakqwy** [comment]
other notes: STD servo lighting scheme should rest at green; excitatory impulses should cause a white flash but no hyperpolarization; no changes to inhibitory impulses.
